INFO     root:base_test.py:33 ðŸ”¹ GET: https://barrigarest.wcaquino.me/contas
DEBUG    urllib3.connectionpool:connectionpool.py:1049 Starting new HTTPS connection (1): barrigarest.wcaquino.me:443
DEBUG    urllib3.connectionpool:connectionpool.py:544 https://barrigarest.wcaquino.me:443 "GET /contas HTTP/1.1" 401 None
DEBUG    charset_normalizer:api.py:461 Encoding detection: ascii is most likely the one.
INFO     root:base_test.py:60 ðŸ”¹ Complete response: Unauthorized
INFO     root:base_test.py:61 ðŸ”¹ Expected Status Code: 401 | Recebido: 401